-- 0004_flashcard_track_category.sql
-- Additive, nullable classification columns on public.flashcards.
-- Lets flashcards be grouped by high-level track ('clinical' | 'preclinical')
-- and by top-level category (must match an existing AppConfig category string).
-- Both nullable so existing (currently zero) rows and not-yet-categorized
-- content are unaffected. No RLS change required.
--
-- GENERATED by the schema task — NOT yet executed. Run in the Supabase SQL
-- Editor (service role) at the checkpoint. Idempotent via IF NOT EXISTS.

alter table public.flashcards
  add column if not exists track text,        -- 'clinical' | 'preclinical'
  add column if not exists category text;     -- matches AppConfig category strings
